### ISSUE TITLE
[Enchancement] Save extracted values to metadata

### ISSUE THREAD

**Issue by kadykov** [DTN-Public/intake-pattern-catalog#20]
Thank you for this amazing extension! It is very useful to just specify the pattern, and then get all the files.

However, it is not very handy to access the parameters, extracted from the file names.
What do you think if we add the extracted parameters to the metadata dictionary of the entries?

To illustrate how it can be used, let's image that we have a situation from the tutorial:

* bucket-name/folder/a_1.csv
* bucket-name/folder/b_1.csv
* bucket-name/folder/c_1.csv
* bucket-name/folder/a_2.csv
* bucket-name/folder/b_2.csv

```yaml
---
metadata:
  version: 1
sources:
  stuff:
    description: Stuff and things
    driver: pattern_cat
    args:
      urlpath: "s3://bucket-name/folder/{foo}_{bar}.csv"
      driver: csv
```
Then, imagine that we want to do something different depending on the extracted values of the variables `foo` and `bar`. 
In this case, we have to call `catalog.stuff.get_entry_kwarg_sets()`, then filter all the elements that satisfy the criteria, pass and unpack them to `catalog.stuff.get_entry()`, and finally do what we want to do depending on the values of `foo` and `bar`.
```python
for params in catalog.stuff.get_entry_kwarg_sets():
    if params["foo"] == "a":
        do.something(catalog.stuff.get_entry(**params))
        do.another.thing(params["bar"])
```

And I if we update the metadata dictionaries with the extracted values of `foo` and `bar`, then this problem could be solved like this:
```python
for entry in catalog.stuff.values():
    if entry.metadata["foo"] == "a":
        do.something(entry)
        do.another.thing(entry.metadata["bar"])
```
Is it possible to add the extracted values to the metadata?
